---
- name: Create systemd-resolved configuration directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy systemd-resolved configuration
  ansible.builtin.copy:
    src: ./etc/systemd/resolved.conf.d/unbound.conf
    dest: /etc/systemd/resolved.conf.d/unbound.conf
  notify:
    - restart systemd-resolved

- name: Install unbound
  ansible.builtin.apt:
    name:
      - unbound
    state: present

- name: Start unbound
  ansible.builtin.systemd_service:
    name: unbound
    enabled: yes
    state: started

- name: Copy unbound configuration
  ansible.builtin.copy:
    src: ./etc/unbound/unbound.conf
    dest: /etc/unbound/unbound.conf
  notify:
    - restart unbound
